apiVersion: apps/v1
kind: Deployment
metadata:
  name: caroline-api
  spec:
    replica:
    selector:
      matchLabels:
        app: caroline-api
    template:
      metadata:
        labels:
          app: caroline-api
        spec:
          containers:
            - name: caroline-api
              image: us-docker.pkg.dev/cit-262-team1-ez/caroline-api/api-tests
              ports:
                - containerPort: 3000
                resource:
                  limits:
                    cpu: ".5"
                    memory: "500Mi"
                  requests:
                    cpu: ".25"
                    memory: "250Mi"
                  livenessProbe:
                    httpGet:
                      path: /
                      port: 3000
                      scheme: HTTP
                    faliureThreshold: 1
                    periodSeconds: 10
                    timeoutSeconds: 10
                  startupProbe:
                    httpGet:
                      path: /
                      port: 3000
                      scheme: HTTP
                    faliureThreshold: 30
                    periodSeconds: 10
                    timeoutSeconds: 10